sudo: required
language: php
php:
  - 7.1

env:
  global:
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE

script:
  - echo "skipping tests"

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - rpm
            - libaio1

before_install:
  - bash install.sh

