sudo: required
language: php
php:
  - 7.1

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/tester -c tests -s

before_install:
  - bash install.oracle.sh
  - phpenv config-add php.ini
