sudo: required
language: php
php:
  - 7.1

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/tester -c tests/php.ini tests -s

before_install:
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/test_db.sh
  - wget https://raw.githubusercontent.com/accgit/docker/master/docker-oracle/oracle/oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb
  - wget https://raw.githubusercontent.com/accgit/docker/master/docker-oracle/oracle/oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb
  - bash accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash test_db.sh
  - sudo dpkg -i oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb
  - sudo dpkg -i oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb
  - echo 'instantclient,/usr/lib/oracle/12.2/client64/lib' | pecl install oci8
