sudo: required
language: php
php:
  - 7.1

script:
  - echo "skipping tests"

matrix:
  include:
    - os: linux
      dist: xenial

before_install:
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/test_db.sh
  - bash accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash test_db.sh