sudo: required
language: php
php:
  - 7.1

env:
  global:
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
    - LD_LIBRARY_PATH=/u01/app/oracle/product/11.2.0/xe/lib

script:
  - echo "skipping tests"

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - rpm
            - libaio1

before_install:
  - bash install.sh
  - sudo apt-get install alien
  - wget https://raw.githubusercontent.com/accgit/travis-oracle/master/oracle/client/oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm
  - sudo alien -i oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm
  - wget https://raw.githubusercontent.com/accgit/travis-oracle/master/oracle/client/oracle-instantclient12.2-devel-12.2.0.1.0-1.x86_64.rpm
  - sudo alien -i oracle-instantclient12.2-devel-12.2.0.1.0-1.x86_64.rpm
  - export ORACLE_HOME=/usr/lib/oracle/12.2/client64/
  - echo 'instantclient,/usr/lib/oracle/12.2/client64/lib' | pecl install oci8
  - echo "extension = oci8.so" >> ~/.phpenv/versions/$(phpenv 7.1)/etc/php.ini
